export const AGENTS = [
  {
    id: "viper",
    name: "서윤",
    call: "VIPER",
    role: "정찰병",
    gender: "여성",
    color: "#c2ed65",
    hp: 100,
    damage: 28,
    armor: 8,
    range: 32,
    speed: 6.4,
    magazine: 24,
    cooldown: 1,
    heal: 30,
    trait: "빠른 기동 · 사거리 32m",
    story: "가장 먼저 진입하고, 가장 마지막에 떠난다.",
    weapon: "VX-24 카빈",
    number: "01",
  },
  {
    id: "bastion",
    name: "태오",
    call: "BASTION",
    role: "수호자",
    gender: "남성",
    color: "#efbe63",
    hp: 145,
    damage: 25,
    armor: 24,
    range: 25,
    speed: 4.8,
    magazine: 28,
    cooldown: 1,
    heal: 30,
    trait: "최대 체력 +45% · 강화 장갑",
    story: "무너진 방어선의 마지막 한 사람.",
    weapon: "BT-28 전투 산탄총",
    number: "02",
  },
  {
    id: "pulse",
    name: "미라",
    call: "PULSE",
    role: "전투 의무관",
    gender: "여성",
    color: "#6bdad0",
    hp: 110,
    damage: 24,
    armor: 12,
    range: 26,
    speed: 5.6,
    magazine: 24,
    cooldown: 0.72,
    heal: 55,
    trait: "치유량 +83% · 기술 쿨다운 -28%",
    story: "심장 박동이 들리는 한, 포기는 없다.",
    weapon: "PL-24 펄스 라이플",
    number: "03",
  },
  {
    id: "reaper",
    name: "레온",
    call: "REAPER",
    role: "돌격병",
    gender: "남성",
    color: "#f28b65",
    hp: 105,
    damage: 36,
    armor: 6,
    range: 25,
    speed: 5.3,
    magazine: 32,
    cooldown: 1.1,
    heal: 30,
    trait: "공격력 +29% · 대용량 탄창",
    story: "공포가 오기 전에, 먼저 방아쇠를 당긴다.",
    weapon: "RP-32 돌격소총",
    number: "04",
  },
  {
    id: "archer",
    name: "하린",
    call: "SYLVA",
    role: "독화살 궁수",
    gender: "여성",
    color: "#a3dc91",
    hp: 92,
    damage: 44,
    armor: 5,
    range: 34,
    speed: 6.5,
    magazine: 12,
    cooldown: 0.85,
    heal: 25,
    trait: "2명 관통 · 독 피해 · 다중 사격",
    story: "바람이 지나간 자리에는 화살만 남는다.",
    weapon: "실바 장궁",
    number: "05",
  },
  {
    id: "sniper",
    name: "도현",
    call: "SPECTER",
    role: "저격수",
    gender: "남성",
    color: "#9dbbfd",
    hp: 85,
    damage: 82,
    armor: 4,
    range: 48,
    speed: 4.9,
    magazine: 5,
    cooldown: 1.2,
    heal: 25,
    trait: "3명 관통 · 18m 밖 피해 +50%",
    story: "한 번의 호흡, 한 발의 결말.",
    weapon: "SP-05 대물 저격총",
    number: "06",
  },
  {
    id: "gale",
    name: "유진",
    call: "GALE",
    role: "자기장 검객",
    gender: "남성",
    color: "#b5a0ff",
    hp: 130,
    damage: 54,
    armor: 16,
    range: 4.5,
    speed: 6.6,
    magazine: 30,
    cooldown: 0.9,
    heal: 30,
    trait: "전방 부채꼴 베기 · 3타 강화",
    story: "부서진 궤도에서 벼린 자력의 칼날.",
    weapon: "월영 자기장 대곡도",
    number: "07",
  },
  {
    id: "lumen",
    name: "세라",
    call: "LUMEN",
    role: "프리즘 술사",
    gender: "여성",
    color: "#ffafd4",
    hp: 100,
    damage: 32,
    armor: 7,
    range: 18,
    speed: 6,
    magazine: 18,
    cooldown: 0.85,
    heal: 40,
    trait: "왕복 구체 · 왕복 각각 명중",
    story: "잃어버린 신호를 빛의 조각에 담는다.",
    weapon: "삼중 프리즘",
    number: "08",
  },
  {
    id: "nova",
    name: "카이",
    call: "NOVA",
    role: "중력 건틀릿",
    gender: "남성",
    color: "#76ccff",
    hp: 105,
    damage: 38,
    armor: 9,
    range: 30,
    speed: 6.2,
    magazine: 20,
    cooldown: 0.85,
    heal: 25,
    trait: "직선 에너지탄 · 충전 3갈래",
    story: "중력 코어를 맨손으로 제어하는 개척자.",
    weapon: "중력 가속 건틀릿",
    number: "09",
  },
];
export const SKILLS = [
  {
    id: "shock",
    name: "충격파",
    icon: "◎",
    detail: "주변 12m에 100 + 레벨 보너스 피해",
    cooldown: 16,
  },
  {
    id: "heal",
    name: "응급 회복",
    icon: "✚",
    detail: "체력 회복 · 의무관 효과 강화",
    cooldown: 22,
  },
  {
    id: "freeze",
    name: "빙결장",
    icon: "❄",
    detail: "주변 18m 적을 6초간 둔화",
    cooldown: 20,
  },
];
export const STAGES = [
  {
    name: "격리 구역",
    code: "QUARANTINE BLOCK",
    color: "#c2ed65",
    fog: 0x27312a,
    sky: 0x303c35,
  },
  {
    name: "잿빛 공업지대",
    code: "ASH INDUSTRIAL",
    color: "#efbe63",
    fog: 0x342c27,
    sky: 0x41382f,
  },
  {
    name: "제로 그라운드",
    code: "GROUND ZERO",
    color: "#6bdad0",
    fog: 0x203239,
    sky: 0x293d47,
  },
];
export const UPGRADES = [
  {
    id: "damage",
    name: "고밀도 탄환",
    stat: "공격력",
    description: "공격력 +7",
    icon: "↗",
    cost: 80,
  },
  {
    id: "armor",
    name: "복합 장갑",
    stat: "방어력",
    description: "방어력 +5 · 체력 +15 회복",
    icon: "◇",
    cost: 70,
  },
  {
    id: "range",
    name: "정밀 총열",
    stat: "사거리",
    description: "사거리 +5m",
    icon: "⌖",
    cost: 60,
  },
];
export const ENEMIES = {
  walker: {
    name: "감염자",
    hp: 65,
    speed: 1.65,
    damage: 13,
    reward: 25,
    xp: 24,
    color: 0x6c7950,
    scale: 1,
  },
  runner: {
    name: "추적자",
    hp: 48,
    speed: 3.05,
    damage: 10,
    reward: 35,
    xp: 32,
    color: 0x9a7656,
    scale: 0.88,
  },
  brute: {
    name: "변이체",
    hp: 210,
    speed: 1.2,
    damage: 26,
    reward: 80,
    xp: 70,
    color: 0x716b65,
    scale: 1.4,
  },
  boss: {
    name: "알파",
    hp: 850,
    speed: 1.35,
    damage: 32,
    reward: 350,
    xp: 200,
    color: 0x8c5143,
    scale: 2,
  },
};
