export const SPECIAL_ATTACKS = {
  gale: {
    name: "극성 회전베기",
    count: 1,
    spread: 0,
    multiplier: 2.5,
    pierce: 12,
    caption: "360도 검무 · 극성 폭풍",
  },
  lumen: {
    name: "분광 삼중구",
    count: 3,
    spread: 0.28,
    multiplier: 1.5,
    pierce: 8,
    caption: "8방향 왕복 · 프리즘 개화",
  },
  nova: {
    name: "중력 삼연포",
    count: 3,
    spread: 0.14,
    multiplier: 1.7,
    pierce: 3,
    caption: "집속 광선 · 중력 관통",
  },
  viper: {
    name: "니들 버스트",
    count: 3,
    spread: 0.035,
    multiplier: 1.4,
    pierce: 2,
    caption: "정밀 관통 · 집중 사격",
  },
  bastion: {
    name: "브리치 샷",
    count: 9,
    spread: 0.08,
    multiplier: 0.7,
    pierce: 1,
    caption: "충격 산탄 · 방어 진형",
  },
  pulse: {
    name: "공명 구체",
    count: 1,
    spread: 0,
    multiplier: 3,
    pierce: 3,
    caption: "회복 파동 · 공명 방출",
  },
  reaper: {
    name: "헬릭스 탄막",
    count: 7,
    spread: 0.045,
    multiplier: 0.85,
    pierce: 1,
    caption: "과충전 탄막 · 화력 집중",
  },
  archer: {
    name: "가시 부채",
    count: 5,
    spread: 0.13,
    multiplier: 1.2,
    pierce: 2,
    caption: "독화살 폭우 · 사냥 개시",
  },
  sniper: {
    name: "레일 랜스",
    count: 1,
    spread: 0,
    multiplier: 3.5,
    pierce: 5,
    caption: "장거리 관통 · 목표 처형",
  },
};
export const CHARGE_SECONDS = 0.8;
